### ISSUE TITLE
Does not work with Atom 1.20.1 and Ansible 2.4.0.0

### ISSUE THREAD

**Issue by pruchai** [autocomplete-python/autocomplete-python#342]
### Steps to Reproduce

1. Restart Atom of reload window

**Expected behavior:** 

No Error Message

**Actual behavior:** 

```
Uncaught Error: Command failed: /usr/bin/python "/Users/<user>/.atom/packages/autocomplete-ansible/lib/parse_ansible.py"
Traceback (most recent call last):
  File "/Users/<user>/.atom/packages/autocomplete-ansible/lib/parse_ansible.py", line 11, in <module>
    from ansible.plugins import lookup_loader, module_loader
ImportError: cannot import name lookup_loader


    at ChildProcess.exithandler (child_process.js:223:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
/Users/<user>/.atom/packages/sync-settings/lib/sync-settings.coffee:118 
```

```
$ python --version
Python 2.7.10
```
```
$ apm list | grep autocomplete-python
├── autocomplete-python@1.10.3
```
```
$ ansible --version
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/var/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

**Comment by erioshi** [comment]
I am also experiencing this.  Vanilla Ubuntu 16.04 LTS with Ansible and Atom installed.
`autocomplete-python traceback output:
Command failed: /usr/bin/python "/home/someuser/.atom/packages/autocomplete-ansible/lib/parse_ansible.py"
Traceback (most recent call last):
  File "/home/someuser/.atom/packages/autocomplete-ansible/lib/parse_ansible.py", line 11, in <module>
    from ansible.plugins import lookup_loader, module_loader
ImportError: cannot import name lookup_loader`

**Comment by jpartain89** [comment]
I am experiencing the exact error output that @erioshi listed:

```
Command failed: /usr/local/opt/python/bin/python2.7 "/Users/$USER/.atom/packages/autocomplete-ansible/lib/parse_ansible.py"
Traceback (most recent call last):
  File "/Users/$USER/.atom/packages/autocomplete-ansible/lib/parse_ansible.py", line 11, in <module>
    from ansible.plugins import lookup_loader, module_loader
ImportError: cannot import name lookup_loader
```

(Removed my username from output, as unneeded....)

This is SUPER annoying, as I use ansible a bunch.... 

I'm on:

- `Atom 1.21.0-beta1`
- `Autocomplete-Python@1.10.3`
- `Ansible 2.4.0.0`
- `Python Version 2.7.14 (default, Sep 25 2017, 09:54:19) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]`
  - The python's info was from the `--version` output of Ansible... If it helps?

Please, let us know if ANY more info is needed, def wanting to help fix this!

**Comment by sadovnychyi** [comment]
The error is raised from ansible package and is not related to autocomplete-python, especially since it's appears when this plugin is removed.

It is titled as autocomplete-python because original author didn't modify error message string [here](https://github.com/h-hirokawa/atom-autocomplete-ansible/blob/eb7d7497aa30a3a782d1e0eca556dc2fbf309a03/lib/provider.js#L48).

Please refer to this issue: https://github.com/h-hirokawa/atom-autocomplete-ansible/issues/18

**Comment by erioshi** [comment]
Thank you for the info.

The issue has cleared itself up when I updated both Atom and my plugins earlier today.
