### ISSUE TITLE
Autocomplete not working with Jedi 0.18 and Miniconda

### ISSUE THREAD

**Issue by alex180500** [autocomplete-python/autocomplete-python#452]
### Steps to Reproduce

I installed the autocomplete-python package with my Python 3.8.8 Miniconda installation with Jedi 0.18 (everything is updated).
The package folders get recognized correctly with the Miniconda folders, but it gives an error and the suggestions don't work.

**Actual behavior:**

Looks like this error originated from Jedi. Please do not report such issues in autocomplete-python issue tracker. Report them directly to Jedi. Turn off outputProviderErrors setting to hide such errors in future. Traceback output:

```py
Traceback (most recent call last):
  File "C:\Users\aless\.atom\packages\autocomplete-python\lib/completion.py", line 378, in watch
    self._process_request(request)
  File "C:\Users\aless\.atom\packages\autocomplete-python\lib/completion.py", line 338, in _process_request
    script = jedi.api.Script(
TypeError: __init__() got an unexpected keyword argument 'source'
```

**Comment by alexladda** [comment]
Getting the same issue with Jedi 0.18 - seems like Jedi changed their API in the last version:

[Jedi Changelog](https://github.com/davidhalter/jedi/blob/master/CHANGELOG.rst)


This will purge 0.18 and install the previous version, which worked for me:
`pip install 'jedi==0.17.2' --force-reinstall`

**Comment by alex180500** [comment]
I can confirm jedi 0.17.2 works fine, seems like the API changed, removing the `source` kwarg.
A simple fix seem to sobsitute the `source` parameter with `code` which should do the same thing according to the old api here:

https://jedi.readthedocs.io/en/v0.17.2/_modules/jedi/api.html#Script
