### ISSUE TITLE
1.8.22 Error with Hyperclick goto definition

### ISSUE THREAD

**Issue by moxuz** [autocomplete-python/autocomplete-python#262]
After updating to 1.8.22 I am unable to cmd+click using hyperclick to go to definition. The underline no longer shows up, and I am getting this in my console every time I hover over a word.
```
/Users/christophepouliot/.atom/packages/hyperclick/lib/HyperclickForTextEditor.js:259 Error getting Hyperclick suggestion: TypeError: Cannot read property 'debug' of undefined
    at constructor.getSuggestionForWord (/Users/christophepouliot/.atom/packages/autocomplete-python/lib/hyperclick-provider.coffee:19:11)
    at v (/Users/christophepouliot/.atom/packages/hyperclick/lib/Hyperclick.js:193:24)
    at /Users/christophepouliot/.atom/packages/hyperclick/lib/Hyperclick.js:22:52
    at next (<anonymous>)
    at step (/Users/christophepouliot/.atom/packages/hyperclick/lib/Hyperclick.js:39:273)
    at /Users/christophepouliot/.atom/packages/hyperclick/lib/Hyperclick.js:39:443
    at /Users/christophepouliot/.atom/packages/hyperclick/lib/Hyperclick.js:39:99
    at Hyperclick.getSuggestion (/Users/christophepouliot/.atom/packages/hyperclick/lib/Hyperclick.js:169:14)
    at HyperclickForTextEditor.<anonymous> (/Users/christophepouliot/.atom/packages/hyperclick/lib/HyperclickForTextEditor.js:246:63)
    at next (<anonymous>)
    at step (/Users/christophepouliot/.atom/packages/hyperclick/lib/HyperclickForTextEditor.js:17:273)
    at /Users/christophepouliot/.atom/packages/hyperclick/lib/HyperclickForTextEditor.js:17:443
    at HyperclickForTextEditor.<anonymous> (/Users/christophepouliot/.atom/packages/hyperclick/lib/HyperclickForTextEditor.js:17:99)
    at HyperclickForTextEditor._onKeyDown (/Users/christophepouliot/.atom/packages/hyperclick/lib/HyperclickForTextEditor.js:198:14)
```

Reverting back to version 1.8.20 fixes the issue.

I am running
Hyperclick:  0.0.39
OSX Sierra:  10.12.1
Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

Thanks :)
